# s1,s2={1,2,3,4,5},{4,5,6,7,8}
# print(s1.union(s2))
# print(s1.intersection(s2))
# print(s1.difference(s2))
# print(s1.symmetric_difference(s2))
# s1.intersection_update(s2)
# print(s1)
# print(s2)
# s1.difference_update(s2)
# print(s1)
# print(s2)
# s1,s2={1,2,3,4,5,6,7,8,9},{5,6,7,8,9}
# print(s1.issuperset(s2))
# print(s2.issuperset(s1))
# print(s1.issubset(s2))
# print(s2.issubset(s1))
# s1,s2={1,2,3,4,5},{5,6,7,8,9}
# print(s1.isdisjoint(s2))
# print(s2.isdisjoint(s1))
# s1,s2={1,2,3},{3,4,5}
# print(s1.isdisjoint(s2))
# print(s2.isdisjoint(s1))
# s={1,2,3,'python','java'}
# s1=s.copy()
# print(s1)
# print(id(s1),id(s))
# s.clear()
# print(s)
# del s
# print(s)
# s.add('php')
# print(s)
# s.update({6,5,4,3})
# print(s)
# print(s.pop())
# s.remove('python')
# print(s)
# s.discard('anuj')
# print(s)
# s='python'
# l=[10,20,30,'python']
# t=[1,2,3,'python']
# fs1=frozenset(s)
# print(fs1,type(fs1))
# fs2=frozenset(l)
# print(fs2,type(fs2))
# fs3=frozenset(t)
# print(fs3,type(fs3))
# print(len(fs1))
# print(max(fs1))
# print(id(fs1))
# print(min(fs1))
# # print(sum(fs1))
# print(len(fs2))
# print(max(fs2))
# fs1=frozenset({1,2,3,4,5})
# fs2=frozenset({4,5,6,7,8})
# print(fs1.union(fs2))
# print(fs1.intersection(fs2))
# print(fs1.difference(fs2))
# print(fs1.symmetric_difference(fs2))
# print(fs1.issuperset(fs2))
# print(fs1.issubset(fs2))
# print(fs1.isdisjoint(fs2))

# l=[1,2,3,4,55]
# l.insert(5,9)
# print(l)
# keys=[1,2,3,4]
# values=[10,20,30,40]
# data=dict(zip(keys,values))
# print(data)

a,b=int(input("Enter a number : ")),int(input("Enter a number : "))
print("a = ",a)
print("b = ",b)